# supabase/config.toml

# 这是项目的唯一标识，必须与您Supabase项目设置里的 "Project ID" 完全一致。
project_id = "wfsuazmffjdzzwuylknq"

[functions.telegram-bot]
# 【核心配置】这行代码强制告诉Supabase，这个函数必须使用Docker来部署！
import_map = "./supabase/functions/telegram-bot/import_map.json"
